# Generated by Django 4.1.5 on 2023-06-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "fathers_name",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        null=True, verbose_name="Дата рождения в формате ГГГГ-ММ-ДД"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Телефон"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="visit",
            name="client_visiting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.customer",
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
