# Generated by Django 4.1.5 on 2023-05-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_specialization_visit_duration_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_finish_time",
            field=models.TimeField(blank=True, default="17:00"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_start_time",
            field=models.TimeField(blank=True, default="08:00"),
        ),
    ]
