# Generated by Django 4.1.5 on 2023-06-20 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_customer_alter_visit_client_visiting_delete_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="client_visiting",
            new_name="customer_visiting",
        ),
    ]
