# Generated by Django 4.1.5 on 2023-05-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
