# Generated by Django 4.1.5 on 2023-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_client_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="specialization",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
