# Generated by Django 4.1.5 on 2023-05-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_doctor_slug_specialization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
