# Generated by Django 4.1.5 on 2023-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_doctor_slug_alter_specialization_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="lunch_finish_time",
            field=models.TimeField(blank=True, default="08:00"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="lunch_start_time",
            field=models.TimeField(blank=True, default="08:00"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="working_days",
            field=models.IntegerField(blank=True, default="1234567"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_finish_time",
            field=models.TimeField(default="17:00"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_start_time",
            field=models.TimeField(default="08:00"),
        ),
    ]
