# Generated by Django 4.1.5 on 2023-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_doctor_lunch_finish_time_doctor_lunch_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="lunch_finish_time",
            field=models.TimeField(default="13:00"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="lunch_start_time",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_days",
            field=models.IntegerField(default="1234567"),
        ),
    ]
