# Generated by Django 4.1.5 on 2023-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="client",
            name="fathers_name",
            field=models.CharField(max_length=255, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, null=True, verbose_name="Телефон"),
        ),
    ]
